- hosts: all
  become: true
  vars:
    - install_directory: /opt/
      DOCKER_COMPOSE_VERSION: "1.25.1"
      USER: "ryanpurchase288_rp"
  tasks:
    - name: Install Requirements for Docker
      apt:
        pkg: # this allows us to install multiple things at once
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        state: latest
        update_cache: true


    - name: Add official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest
        update_cache: true

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ USER }} to docker group
      user:
        name: "{{ USER }}"
        groups: "docker"
        append: "yes"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
